### ISSUE TITLE
Bot crashes

### ISSUE THREAD

**Issue by laura240406** [TheCataliasTNT2k/placebot#4]
```
using config.json as config
Obtaining CSRF token...
Logging in...
Authorization successful!
Obtaining access token...
Logged in as CeleryCharacter6549


1 accounts logged in

Attempting to place for: CeleryCharacter6549

Refreshing target configuration...

Getting board


Error encountered while running bot: 
Traceback (most recent call last):
  File "/root/placebot/src/placebot.py", line 106, in <module>
    run_bot()
  File "/root/placebot/src/placebot.py", line 98, in run_bot
    run_board_watcher_placer(placers)
  File "/root/placebot/src/placebot.py", line 58, in run_board_watcher_placer
    placer.update_board()
  File "/root/placebot/src/placer.py", line 179, in update_board
    self.update_canvas(canvas_id)
  File "/root/placebot/src/placer.py", line 189, in update_canvas
    ws = create_connection("wss://gql-realtime-2.reddit.com/query")
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 515, in create_connection
    websock.connect(url, **options)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/lib/python3/dist-packages/websocket/_handshake.py", line 80, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/lib/python3/dist-packages/websocket/_handshake.py", line 165, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden

Restarting...
```

I'm running this on a headless Debian 10 machine.

**Comment by NYC00kie** [comment]
got the same Error.
Seems like the Server is Blocking the Request.
Thats indicated by the 403 Forbidden Error Code

**Comment by NYC00kie** [comment]
seems fixed
